name: GitHub Actions integration for DAST Scan with ZAP
on: [push]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
            token: ${{ secrets.GITZHUB_TOKEN }}
            docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
            target: 'http://testphp.vulnweb.com/'
            rules_file_name: '.zap/rules.tsv'
            cmd_options: '-a'
